# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: registry.hub.docker.com/aws_training

stages:
- stage: Build_and_Push 
  displayName: Build image
  jobs:  
  - job: Build_Push
    displayName: Build and push docker image to docker hub
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
         $(tag)

    - task: Docker@2
      displayName: Push an image
      inputs:
       containerRegistry: 'Docker Hub'
       command: push
      