# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: aws_training
  repository: suresh2203

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
         $(tag)

- stage: Push image
  displayName: Push image
  jobs:
  - job: Push
    displayName: Push image to docker hub
    steps:       
    - task: Docker@2
      displayName: Push image
      inputs:
       containerRegistry: 'Docker Hub'
       repository: $(repository)
       command: push