
#version: 2.1
jobs:
 build: 
  docker:
  - image: buildpack-deps:trusty 
 
  steps:
   - checkout
   - setup_remote_docker
   - run: |
     docker build -t $imageName:$CIRCLE_BUILD_NUM Dockerfile
   
